services:
  qdrant:
    image: qdrant/qdrant
    restart: always
    volumes:
      - ./qdrant/qdrant_storage:/qdrant/storage:z
    ports:
      - 6333:6333
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/src:/usr/src/backend/src
    ports:
      - 3001:3001
    networks: 
      - app-network
    depends_on:
      - qdrant
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/frontend/src
    environment:
       - CHOKIDAR_USEPOLLING=true
networks: 
  app-network:
    driver: bridge 